// Generated by Grafana k6 Studio (1.9.0) on 2025-12-09T17:28:59.218Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"macOS"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-GB,en-US;q=0.9,en;q=0.8`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://ailh.ai/login`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `POST`,
        "Access-Control-Request-Headers": `content-type,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/users/login`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "Content-Type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        Accept: `*/*`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/users/login`;
    resp = http.request(
      "POST",
      url,
      `{"email":"demo@hog.com","password":"DemoHog@123"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 500": (r) => r.status === 500 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/summary`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/summary`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/summary`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/summary`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/dispatch`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/dispatch`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/dispatch`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/dispatch`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sensor/dispatch`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sensor/dispatch`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sensor/dispatch`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sensor/dispatch`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sites/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sensor/?zone_id=1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/?zone_id=1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sites/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sensor/?zone_id=1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/?zone_id=1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/roles/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/users/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/teams/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/roles/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/users/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/teams/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections?time_unit=24`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections?time_unit=24`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/summary`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/summary`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/alert_dashboard/list`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections?time_unit=24`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/events/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/water_loss/zone_sections?time_unit=24`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/33?pipeline_group_id=2&pipeline_sequence=1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/1?pipeline_sequence=3`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_zones/33?pipeline_group_id=2&pipeline_sequence=1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/1?pipeline_sequence=3`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/112?pipeline_sequence=1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/sections/112?pipeline_sequence=1`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `GET`,
        "Access-Control-Request-Headers": `authorization,organization`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/pipelines_group/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        Connection: `keep-alive`,
        organization: `HOG`,
        "sec-ch-ua-platform": `"macOS"`,
        Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjUzODcxODR9.pZCBwhrSTU5XN9GTk_qn2VqdElGRymQuHts4yzFYfAU`,
        Accept: `application/json, text/plain, */*`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        Origin: `https://ailh.ai`,
        "Sec-Fetch-Site": `cross-site`,
        "Sec-Fetch-Mode": `cors`,
        "Sec-Fetch-Dest": `empty`,
        "Accept-Encoding": `gzip, deflate, br, zstd`,
        "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
      },
      cookies: {},
    };

    url = http.url`https://pipeline-dev-b2bygkfbaaa0eab8.westcentralus-01.azurewebsites.net/v1/dashboard/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
